# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/user/MyFile/tsdb

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/user/MyFile/tsdb

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/MyFile/tsdb/CMakeFiles /home/user/MyFile/tsdb//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/MyFile/tsdb/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named FSSCoreCommon

# Build rule for target.
FSSCoreCommon: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FSSCoreCommon
.PHONY : FSSCoreCommon

# fast build rule for target.
FSSCoreCommon/fast:
	$(MAKE) $(MAKESILENT) -f fss-core/common/CMakeFiles/FSSCoreCommon.dir/build.make fss-core/common/CMakeFiles/FSSCoreCommon.dir/build
.PHONY : FSSCoreCommon/fast

#=============================================================================
# Target rules for targets named DPFClient

# Build rule for target.
DPFClient: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DPFClient
.PHONY : DPFClient

# fast build rule for target.
DPFClient/fast:
	$(MAKE) $(MAKESILENT) -f fss-core/DPF-source/CMakeFiles/DPFClient.dir/build.make fss-core/DPF-source/CMakeFiles/DPFClient.dir/build
.PHONY : DPFClient/fast

#=============================================================================
# Target rules for targets named DPFServer

# Build rule for target.
DPFServer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DPFServer
.PHONY : DPFServer

# fast build rule for target.
DPFServer/fast:
	$(MAKE) $(MAKESILENT) -f fss-core/DPF-source/CMakeFiles/DPFServer.dir/build.make fss-core/DPF-source/CMakeFiles/DPFServer.dir/build
.PHONY : DPFServer/fast

#=============================================================================
# Target rules for targets named DCFClient

# Build rule for target.
DCFClient: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DCFClient
.PHONY : DCFClient

# fast build rule for target.
DCFClient/fast:
	$(MAKE) $(MAKESILENT) -f fss-core/DCF-source/CMakeFiles/DCFClient.dir/build.make fss-core/DCF-source/CMakeFiles/DCFClient.dir/build
.PHONY : DCFClient/fast

#=============================================================================
# Target rules for targets named DCFServer

# Build rule for target.
DCFServer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DCFServer
.PHONY : DCFServer

# fast build rule for target.
DCFServer/fast:
	$(MAKE) $(MAKESILENT) -f fss-core/DCF-source/CMakeFiles/DCFServer.dir/build.make fss-core/DCF-source/CMakeFiles/DCFServer.dir/build
.PHONY : DCFServer/fast

#=============================================================================
# Target rules for targets named DPF_unit_test

# Build rule for target.
DPF_unit_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DPF_unit_test
.PHONY : DPF_unit_test

# fast build rule for target.
DPF_unit_test/fast:
	$(MAKE) $(MAKESILENT) -f fss-core/tests/CMakeFiles/DPF_unit_test.dir/build.make fss-core/tests/CMakeFiles/DPF_unit_test.dir/build
.PHONY : DPF_unit_test/fast

#=============================================================================
# Target rules for targets named DCF_unit_test

# Build rule for target.
DCF_unit_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DCF_unit_test
.PHONY : DCF_unit_test

# fast build rule for target.
DCF_unit_test/fast:
	$(MAKE) $(MAKESILENT) -f fss-core/tests/CMakeFiles/DCF_unit_test.dir/build.make fss-core/tests/CMakeFiles/DCF_unit_test.dir/build
.PHONY : DCF_unit_test/fast

#=============================================================================
# Target rules for targets named EMPNetIOUnitTest

# Build rule for target.
EMPNetIOUnitTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 EMPNetIOUnitTest
.PHONY : EMPNetIOUnitTest

# fast build rule for target.
EMPNetIOUnitTest/fast:
	$(MAKE) $(MAKESILENT) -f network-emp/tests/CMakeFiles/EMPNetIOUnitTest.dir/build.make network-emp/tests/CMakeFiles/EMPNetIOUnitTest.dir/build
.PHONY : EMPNetIOUnitTest/fast

#=============================================================================
# Target rules for targets named protos

# Build rule for target.
protos: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 protos
.PHONY : protos

# fast build rule for target.
protos/fast:
	$(MAKE) $(MAKESILENT) -f network/core/CMakeFiles/protos.dir/build.make network/core/CMakeFiles/protos.dir/build
.PHONY : protos/fast

#=============================================================================
# Target rules for targets named query_proto

# Build rule for target.
query_proto: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 query_proto
.PHONY : query_proto

# fast build rule for target.
query_proto/fast:
	$(MAKE) $(MAKESILENT) -f network/core/CMakeFiles/query_proto.dir/build.make network/core/CMakeFiles/query_proto.dir/build
.PHONY : query_proto/fast

#=============================================================================
# Target rules for targets named AggTree

# Build rule for target.
AggTree: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AggTree
.PHONY : AggTree

# fast build rule for target.
AggTree/fast:
	$(MAKE) $(MAKESILENT) -f secure-indices/core/CMakeFiles/AggTree.dir/build.make secure-indices/core/CMakeFiles/AggTree.dir/build
.PHONY : AggTree/fast

#=============================================================================
# Target rules for targets named DPFTable

# Build rule for target.
DPFTable: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DPFTable
.PHONY : DPFTable

# fast build rule for target.
DPFTable/fast:
	$(MAKE) $(MAKESILENT) -f secure-indices/core/CMakeFiles/DPFTable.dir/build.make secure-indices/core/CMakeFiles/DPFTable.dir/build
.PHONY : DPFTable/fast

#=============================================================================
# Target rules for targets named DCFTable

# Build rule for target.
DCFTable: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DCFTable
.PHONY : DCFTable

# fast build rule for target.
DCFTable/fast:
	$(MAKE) $(MAKESILENT) -f secure-indices/core/CMakeFiles/DCFTable.dir/build.make secure-indices/core/CMakeFiles/DCFTable.dir/build
.PHONY : DCFTable/fast

#=============================================================================
# Target rules for targets named Common

# Build rule for target.
Common: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Common
.PHONY : Common

# fast build rule for target.
Common/fast:
	$(MAKE) $(MAKESILENT) -f secure-indices/core/CMakeFiles/Common.dir/build.make secure-indices/core/CMakeFiles/Common.dir/build
.PHONY : Common/fast

#=============================================================================
# Target rules for targets named AggTreeUnitTest

# Build rule for target.
AggTreeUnitTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AggTreeUnitTest
.PHONY : AggTreeUnitTest

# fast build rule for target.
AggTreeUnitTest/fast:
	$(MAKE) $(MAKESILENT) -f secure-indices/tests/CMakeFiles/AggTreeUnitTest.dir/build.make secure-indices/tests/CMakeFiles/AggTreeUnitTest.dir/build
.PHONY : AggTreeUnitTest/fast

#=============================================================================
# Target rules for targets named DPFTableUnitTest

# Build rule for target.
DPFTableUnitTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DPFTableUnitTest
.PHONY : DPFTableUnitTest

# fast build rule for target.
DPFTableUnitTest/fast:
	$(MAKE) $(MAKESILENT) -f secure-indices/tests/CMakeFiles/DPFTableUnitTest.dir/build.make secure-indices/tests/CMakeFiles/DPFTableUnitTest.dir/build
.PHONY : DPFTableUnitTest/fast

#=============================================================================
# Target rules for targets named DCFTableUnitTest

# Build rule for target.
DCFTableUnitTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DCFTableUnitTest
.PHONY : DCFTableUnitTest

# fast build rule for target.
DCFTableUnitTest/fast:
	$(MAKE) $(MAKESILENT) -f secure-indices/tests/CMakeFiles/DCFTableUnitTest.dir/build.make secure-indices/tests/CMakeFiles/DCFTableUnitTest.dir/build
.PHONY : DCFTableUnitTest/fast

#=============================================================================
# Target rules for targets named DCFTableICUnitTest

# Build rule for target.
DCFTableICUnitTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DCFTableICUnitTest
.PHONY : DCFTableICUnitTest

# fast build rule for target.
DCFTableICUnitTest/fast:
	$(MAKE) $(MAKESILENT) -f secure-indices/tests/CMakeFiles/DCFTableICUnitTest.dir/build.make secure-indices/tests/CMakeFiles/DCFTableICUnitTest.dir/build
.PHONY : DCFTableICUnitTest/fast

#=============================================================================
# Target rules for targets named DCFTableParallelICUnitTest

# Build rule for target.
DCFTableParallelICUnitTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DCFTableParallelICUnitTest
.PHONY : DCFTableParallelICUnitTest

# fast build rule for target.
DCFTableParallelICUnitTest/fast:
	$(MAKE) $(MAKESILENT) -f secure-indices/tests/CMakeFiles/DCFTableParallelICUnitTest.dir/build.make secure-indices/tests/CMakeFiles/DCFTableParallelICUnitTest.dir/build
.PHONY : DCFTableParallelICUnitTest/fast

#=============================================================================
# Target rules for targets named DPFTableParallelUnitTest

# Build rule for target.
DPFTableParallelUnitTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DPFTableParallelUnitTest
.PHONY : DPFTableParallelUnitTest

# fast build rule for target.
DPFTableParallelUnitTest/fast:
	$(MAKE) $(MAKESILENT) -f secure-indices/tests/CMakeFiles/DPFTableParallelUnitTest.dir/build.make secure-indices/tests/CMakeFiles/DPFTableParallelUnitTest.dir/build
.PHONY : DPFTableParallelUnitTest/fast

#=============================================================================
# Target rules for targets named RollUpUnitTest

# Build rule for target.
RollUpUnitTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RollUpUnitTest
.PHONY : RollUpUnitTest

# fast build rule for target.
RollUpUnitTest/fast:
	$(MAKE) $(MAKESILENT) -f secure-indices/tests/CMakeFiles/RollUpUnitTest.dir/build.make secure-indices/tests/CMakeFiles/RollUpUnitTest.dir/build
.PHONY : RollUpUnitTest/fast

#=============================================================================
# Target rules for targets named query_client

# Build rule for target.
query_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 query_client
.PHONY : query_client

# fast build rule for target.
query_client/fast:
	$(MAKE) $(MAKESILENT) -f client/core/CMakeFiles/query_client.dir/build.make client/core/CMakeFiles/query_client.dir/build
.PHONY : query_client/fast

#=============================================================================
# Target rules for targets named bench

# Build rule for target.
bench: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench
.PHONY : bench

# fast build rule for target.
bench/fast:
	$(MAKE) $(MAKESILENT) -f client/tests/CMakeFiles/bench.dir/build.make client/tests/CMakeFiles/bench.dir/build
.PHONY : bench/fast

#=============================================================================
# Target rules for targets named query_server

# Build rule for target.
query_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 query_server
.PHONY : query_server

# fast build rule for target.
query_server/fast:
	$(MAKE) $(MAKESILENT) -f server/core/CMakeFiles/query_server.dir/build.make server/core/CMakeFiles/query_server.dir/build
.PHONY : query_server/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... protos"
	@echo "... AggTree"
	@echo "... AggTreeUnitTest"
	@echo "... Common"
	@echo "... DCFClient"
	@echo "... DCFServer"
	@echo "... DCFTable"
	@echo "... DCFTableICUnitTest"
	@echo "... DCFTableParallelICUnitTest"
	@echo "... DCFTableUnitTest"
	@echo "... DCF_unit_test"
	@echo "... DPFClient"
	@echo "... DPFServer"
	@echo "... DPFTable"
	@echo "... DPFTableParallelUnitTest"
	@echo "... DPFTableUnitTest"
	@echo "... DPF_unit_test"
	@echo "... EMPNetIOUnitTest"
	@echo "... FSSCoreCommon"
	@echo "... RollUpUnitTest"
	@echo "... bench"
	@echo "... query_client"
	@echo "... query_proto"
	@echo "... query_server"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

